### ISSUE TITLE
请问如果有多个句子怎么办呢？

### ISSUE THREAD

**Issue by yuye2133** [indiejoseph/cnn-text-classification-tf-chinese#1]
您好，我看你写的是中文的文本分类，所以就用中文问了
这个demo好像做的是句子级别的分类，但是我想请问下，如果我有多个句子应该怎么办呢？
把channel数改成相应的句子数吗？相应的batch应该选择哪个呢？

希望您有空能回复下，感激不尽

**Comment by indiejoseph** [comment]
你好 , 基本上你可把整份文章當成一句句子輸入, 但句子越長，句子特徵及含義越難分類, CNN 輸入長度（sequence_length）會自動調整到 dataset 中最長的句子長度，其他短句都會被 pad 到跟最長那條句子的長度。
