### ISSUE TITLE
There is no _linear function in TensorFlow 1.0.1

### ISSUE THREAD

**Issue by GabrielLin** [indiejoseph/cnn-text-classification-tf-chinese#11]
I managed to run the code in TF 1.0.1 using the conversion script. However, I still cannot found the _linear function in TF 1.0.1 in text_cnn.py line 14. Could you give some suggestions? Thanks.

**Comment by acalanatha** [comment]
add below, and remove scope parameter while calling:
from tensorflow.contrib.rnn.python.ops.core_rnn_cell_impl import _linear as linear
