### ISSUE TITLE
The model seems not converging?

### ISSUE THREAD

**Issue by tim5go** [indiejoseph/cnn-text-classification-tf-chinese#17]
The training accuracy is fluctuating between 55% -75% even after 800 steps.
I wonder in your case, how many steps did you take to make it converge to 98%?

**Comment by indiejoseph** [comment]
sorry, i forgot, and my log folder deleted accidentally,  but what is the character embedding you using?
I no longer maintains this repo, the code base is out-of-date, you could check my hierarchical attention model: https://github.com/indiejoseph/doc-han-att

**Comment by indiejoseph** [comment]
@tim5go feel free join us Hong Kong Deep Learning Study Group on Facebook: https://www.facebook.com/groups/170776840085989/?ref=bookmarks

**Comment by tim5go** [comment]
I used the default parameter, which I guess it didn't include a pre-trained embedding?

**Comment by indiejoseph** [comment]
yes, i used pre-trained embedding that trained with https://github.com/indiejoseph/chinese-char-rnn, if training without pre-trained embedding that has to take more step to converge

**Comment by tim5go** [comment]
Thanks ! ^^
